spring:
  application:
    name: gateway-server

  cloud:
    gateway:
      mvc:
        routes:
          - id: test-route
            uri: http://localhost:8080
            predicates:
              - Path=/v1/test/**

server:
  port: 7080
